# Generated by Django 5.2 on 2025-04-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iata', models.CharField(max_length=3, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
