# Generated by Django 5.2 on 2025-04-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports_data_fetch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airports',
            table='airports',
        ),
    ]
